### ISSUE TITLE
[1.12.x] Regeneration ability not working like expected?

### ISSUE THREAD

**Issue by JustJinxed** [CyclopsMC/EverlastingAbilities#52] opened 2017-09-22 11:25 UTC
EverlastingAbilities-1.12-1.3.3
CyclopsCore-1.12-0.10.18
Forge 2478 (Milestone)

Regeneration 1..2 doesn't seem to be working. (3 does however) Doesn't appear to be tick related on the cyclops side after looking in on the corelib. Does MC use a time diff to decide if a half-heart gets added (IE Minecraft never sees the buff change from 3 seconds, so it doesn't add health to the player until 2.5 seconds have actually passed) ? If so, is this ability fixable?

**Comment by rubensworks** [comment] 2017-09-22 12:45
Duplicate of #51.

If you can reproduce it _without_ any other mods installed, please let me know.

**Comment by JustJinxed** [comment] 2017-09-23 05:33
I ran it without any other mods but CC and EA, before submitting this. I do need to do an edit though, rank 3 seems to be working fine. But ranks 1 and 2 aren't, and forgot my forge version.

Test: drop lingering poison, wait until you at least have only 8/10 food and less than half life. Pop on rank 1 of regen via totem.. wait.. nada.. Pop on another rank (to 2), wait, nada... Pop on last one (rank 3) ... wooosh -- regen starts going. As a double blind test, the regeneration potions and golden apples themselves seem to work fine. 

I'd build a local version just to check if it's something different from release vs master, but there's a lot of deps that I'm not sure how to address, and they don't look to be setup for download in the build.gradle file. (I'm only quasi apt at that sort of thing, just yet ;) )

**Comment by rubensworks** [comment] 2017-09-23 07:56
I'll have another look at it soon.

**Closed as completed** 2017-09-23 09:29 UTC
Labels: bug, duplicate
