### ISSUE TITLE
Seem to be getting too many rare totems

### ISSUE THREAD

**Issue by faeldray** [CyclopsMC/EverlastingAbilities#88] opened 2018-04-07 20:53 UTC
#### Issue type:

_Only keep the issue types that are applicable._

- :question: Has the drop rate/chest spawn rate of different rarities of totems changed in the last update? I ask because previously, I had seen mostly Rarity 1 totems from mob drops and chests. But last night I was playing for about 3 hours and was only exploring/killing things for some of it, and I managed to get 3 Flight totems and 1 Saturation totem (I have the other Rarity 3 totems turned off). Don't get me wrong, I like getting more than Rarity 1 totems, but this seems a little OP now. 😛

- :heavy_plus_sign: Maybe a solution would be allowing us to modify the drop rates of the different rarity levels?

#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.3.14
- CyclopsCore: 0.11.5
- Minecraft: 1.12.2
- Forge: 14.23.2.2611

**Comment by rubensworks** [comment] 2018-04-08 05:47
That was caused by #84 and #85, will be fixed in the next update.

**Closed as completed by rubensworks** 2018-04-08 05:47 UTC
Labels: bug
