### ISSUE TITLE
Abrupt Crash when loading world

### ISSUE THREAD

**Issue by brisingraerowing** [CyclopsMC/EverlastingAbilities#87] opened 2018-04-07 20:51 UTC
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug
____
#### Short description:
Crash when loading a world.

#### Expected behaviour:
I enter the world and start playing

#### Actual behaviour:
Game crashes and hangs.

#### Steps to reproduce the problem:

1. Try to load a world.
2. Crash.
____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 3.1.14
- CyclopsCore: 0.11.5
- Minecraft: 1.12.2
- Forge: 2654

#### Log file:

[Crash Log](https://gist.github.com/BrisingrAerowing/9254ae62912f858cc852bc905171d265)

**Comment by brisingraerowing** [comment] 2018-04-07 20:52
It looks like this might be related to #85

**Comment by Sunconure11** [comment] 2018-04-08 04:51
I think it is. I received a similar crash, as well.

https://pastebin.com/NpYX8en6

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/NpYX8en6">---- Minecraft Crash Report ----    WARNING: coremods are present:    CTMCorePlu - Pastebin.com</a></strong></div></blockquote>

**Comment by rubensworks** [comment] 2018-04-08 05:44
Duplicate of #85.

**Closed as completed by rubensworks** 2018-04-08 05:44 UTC
Labels: duplicate
