### ISSUE TITLE
Adding entire mod to Friendlies config not protecting mobs of that mod

### ISSUE THREAD

**Issue by PurpleHel** [CyclopsMC/EverlastingAbilities#212] opened 2022-12-29 19:36 UTC
#### Issue type:

- :bug: Bug 

____

#### Short description:

Adding entire mods to the friendly mobs config doesn't seem to be working?

#### Steps to reproduce the problem:

1. Have everlasting and a mod that adds mobs, such as Alex's Mobs
2. Add "alexsmobs:.*", under friendly in config
3. Have Wither ability on
4. Accidentally kill all mobs from Alex's Mobs near you

#### Expected behaviour:

Adding the whole mod to friendlies in config would prevent negative abilities from impacting mobs from that mod.

____

#### Versions:

- This mod: EverlastingAbilities-1.19.2-1.8.2
- Minecraft: 1.19.2
- Forge: 43.2.0
- alexsmobs-1.21.0 (but it applies to other mods that add mobs too, that's just the easiest to test with. Kobolds, for example.)
- -MultiMC version: 0.7.0-develop-3635 (don't think it's relevant, but...)

**Comment by rubensworks** [comment] 2022-12-29 19:36
Thanks for reporting!

**Comment by rubensworks** [comment] 2022-12-30 08:49
This will be caused by the same problem as https://github.com/CyclopsMC/EverlastingAbilities/issues/211, which will be fixed in https://github.com/CyclopsMC/CyclopsCore/commit/5cc45739ed80e79d7711016817ac689e6378ffd2

**Closed as completed by rubensworks** 2022-12-30 08:49 UTC
Labels: bug, mc-1.19
