### ISSUE TITLE
[1.14.4] java.lang.NullPointerException: Ticking entity when attacking a zombie while invisible

### ISSUE THREAD

**Issue by raziel23x** [CyclopsMC/EverlastingAbilities#137] opened 2019-09-27 14:37 UTC
#### Issue type:

- :bug: Bug

____

#### Short description:
If i go back to forge versions 28.0.x the crash goes away but when i update to any version of forge to 28.1.x that is when the crash happens
when attacking a zombie the game crashes
I started looking through all the source code in all the mods that added new mobs or messed with the loot tables for mobs i have loaded none of them have touched the code for the zombie and from talking with Animefan8888 and he said this could be the issue https://www.minecraftforge.net/forum/topic/76145-forge-281x-causing-crash-when-killing-zombies/?tab=comments#comment-366371
https://gitlab.com/Lycanite/LycanitesMobs/issues/582
https://github.com/MinecraftForge/MinecraftForge/issues/6185#issuecomment-535636344

#### Steps to reproduce the problem:

Steps to Reproduce:

1. find or spawn in a zombie
2. attack the zombie while invisible
3. game crashes

#### Expected behaviour:

____

#### Versions:

- This mod: 1.5.5
- Minecraft: 1.14.4
- Forge:  28.1.0-28.1.22

#### Log file:
https://paste.dimdev.org/akonuzitoh.mccrash

**Comment by rubensworks** [comment] 2019-09-27 15:13
Please don't open new issues for the same thing.
Just comment on the previous issue.
Duplicate of #132.

**Closed as completed by rubensworks** 2019-09-27 15:13 UTC
Labels: duplicate
