### ISSUE TITLE
Bug: Night Vision ability doesn't work

### ISSUE THREAD

**Issue by rinart73** [CyclopsMC/EverlastingAbilities#19] opened 2016-09-24 03:51 UTC
Currently Night Vision ability does just nothing (last version, 1.10.2)

**Comment by rubensworks** [comment] 2016-09-24 08:13
Duplicate of #1.
This must be a mod messing with the night vision potion effect, since I can not reproduce this issue.

Are you able to use vanilla night vision potions?
To identify the conflicting mod, you can try removing mods until you see that it works again using binary search.

**Closed as completed** 2016-11-13 12:09 UTC
Labels: duplicate
