### ISSUE TITLE
Conflict with PattysMoreStuff / Any flight item. 

### ISSUE THREAD

**Issue by DraknusX** [CyclopsMC/EverlastingAbilities#150] opened 2019-11-29 01:04 UTC
Hey, 

It looks like the flight ability refuses to function with PattysMoreStuff. My guess is that, like AngelRing, it has a flight item (ring of flight). Seems like a really big issue, because that would make EA incompatible with any mod with any item that gives flight. Any hopes on fixing that?

**Comment by rubensworks** [comment] 2019-11-29 05:50
That mod must be breaking flight from other mods by continuously setting `player.capabilities.allowFlying` to false.
I suggest you report this to the issue tracker of that mod.

Feel free to link back to this issue, or ping me in the issue in case more information is needed for the mod author.

Duplicate of #142.

**Closed as completed by rubensworks** 2019-11-29 05:50 UTC
Labels: duplicate, other mod
