### ISSUE TITLE
[1.10.2] Night Vision is not working

### ISSUE THREAD

**Issue by milano1110** [CyclopsMC/EverlastingAbilities#45] opened 2017-06-02 12:53 UTC
When I try to select Night Vision, it goes to my player, but then does nothing. I've tried it with the rest of my abilities and alone and it is not working.
If you need anymore information, just say it and I'll post it.

Anyway thank you for this mod, I am really enjoying it so far.

Greetings Milano

**Comment by rubensworks** [comment] 2017-06-02 13:03
Duplicate of #1, please continue discussing in that issue.

**Closed as completed by rubensworks** 2017-06-02 13:03 UTC
Labels: duplicate
