### ISSUE TITLE
1.11.2 Stuck invisible

### ISSUE THREAD

**Issue by Centros** [CyclopsMC/EverlastingAbilities#54] opened 2017-09-27 05:01 UTC
First off love the mod. The problem is when I used an invisibility totem the totem disappeared and I got the ability in my list but I wasn't invisible and I couldn't remove it from the list. After some time I got another one used it and this time I became invisible but now I am stuck invisible I cant remove the ability there is one in the active list and one in the none active list. I have a lot of other mods installed and I haven't been able to reproduce this but other than delete my character data I was also wondering if there was a command to remove abilities.

**Comment by rubensworks** [comment] 2017-09-27 06:21
Sounds like an issue caused by conflicting mods. If you can reproduce this with just EA installed, please let me know.
This mod just triggers the invisibility potion effect every few seconds when enabled, so it is impossible for it to cause invisibility to be active if you don't have the ability enabled.

This mods does indeed provide commands to handle abilities, you can use `\everlastingabilities` and tab through the options.

**Comment by Centros** [comment] 2017-09-30 01:40
Alrighty ill give it a few swings when I have some more time off work right now though its asking for the ability Id. I cant seam to find that anywhere when I try the command I cant tab through and if I enter it I get Usage: /everlastingabilities <abilities | config | version>. The config didn't help and if I try abilities I get Usage: /everlastingabilities abilities <add|remove|list> <player> <abilityid> <level>. The only thing that was remotely close was list than player but it didn't provide any ids just the ability an @ symbol and the lvl. Using the remove command with the name didn't work just says Could not find the ability with id "null". 

Anywho for what its worth thank you for the quick response I very much enjoy your mod and plan to try my best to reproduce this problem in a clean environment

**Comment by rubensworks** [comment] 2017-11-11 06:18
@Centros Any updates on this? Will close this otherwise.

**Comment by Centros** [comment] 2017-11-12 00:31
ya I just used another bottle to take the enchantment off thought they were all linked so I didn't know I could do that :P but ya its fixed

**Closed as completed** 2017-11-12 04:02 UTC
