### ISSUE TITLE
Graphical issue within modded dimensions when Night vision skill is enabled

### ISSUE THREAD

**Issue by DatrixTHLK** [CyclopsMC/EverlastingAbilities#25] opened 2016-11-25 05:45 UTC
Hello,

I just now noticed this issue, for some odd reason the modded dimensions (from both utilitiy worlds and Dimensional Resource Dimensions) are pitch black at night time and my character is blinded more or less. Taking off night vision causes issues to vanish.

Picture of issue: http://tinypic.com/r/14dfwut/9

Minecraft 1.10.2
Forge: 12.18.2.2151
Cyclopscore: 0.8.1
Everlastingabilities: 1.2.2

**Comment by rubensworks** [comment] 2016-11-25 08:04
Seems to be another duplicate of #1.
It is very unlikely that this is a problem with this mod, since we just apply the vanilla night vision potion effect.

What happens if you drink a vanilla night vision potion?

**Comment by DatrixTHLK** [comment] 2016-11-25 20:25
I will send this over to [Utilitiy Worlds](https://minecraft.curseforge.com/projects/utility-worlds) and [Dimensional Resources](https://minecraft.curseforge.com/projects/dimensional-resources), seeing that it only happens in modded dimensions. Shouldn't modded dimensions follow the same logic for Vanilla dimensions though? 

Going to test it when I get home later tonight and will let you know the results

**Comment by rubensworks** [comment] 2016-11-25 20:28
I never implemented any custom dimensions myself, but as far as I know, there shouldn't be any difference unless this has been customly implemented by the mod author.

**Comment by DatrixTHLK** [comment] 2016-11-25 21:05
Anyway, the issue has been relayed to both mod authors. Hopefully something will come of it. Thanks for responding.

**Closed as completed** 2016-11-25 21:06 UTC
Labels: duplicate
