### ISSUE TITLE
Flight ability lost on dimension switch need to re-apply

### ISSUE THREAD

**Issue by Crimix** [CyclopsMC/EverlastingAbilities#155] opened 2020-01-25 11:53 UTC
#### Issue type:

- :bug: Bug

____

#### Short description:

Loosing flight when going between dimensions.
This is something many flights mods seem to have some issues with. 
I would expects it has something to do with how the player entity is respawned when switching dimensions.

#### Steps to reproduce the problem:

1. Have flight unlocked.
2. Go to nether though portal.
3. Can no longer fly, without first putting the ability back in the bottle and re-applying it.
4. Then I can fly again. Same thing happens when going back to overworld.

#### Expected behaviour:

I should be able to fly without having to re-apply the ability after each dimension swtich.
____

#### Versions:

- This mod: 1.6.0
- Minecraft: 1.14.4
- Forge: 28.1.109
- Modpack Enigmatic 4 version 0.4.4

**Comment by rubensworks** [comment] 2020-01-25 12:07
Duplicate of #142. This appears to be the angel ring mod misbehaving. Nothing much I can do about this unfortunately...

**Closed as completed** 2020-01-25 12:08 UTC
Labels: other mod

**Comment by Crimix** [comment] 2020-01-25 12:17
Sorry, I will see if I cannot make a PR to the AngelRing mod to make it stop thinking it is the only item allowed to give flight. This is really the only thing we can do
